### ISSUE TITLE
Alt/Opt + S Adds ß to Search Box

### ISSUE THREAD

**Issue by hwrainbird** [cortexrd/Kneuron#11]
Hey Norm,

Firstly, thanks for your work! This is amazing! 

I found one small quirk, when using Opt + S (I'm on Mac so it's Opt instead of Alt) to focus the Search Box it starts typing "ß" in the search

Here's a demo:
![Rainbird Apps Screenshot 2024-11-28 @ 14 42 59](https://github.com/user-attachments/assets/1ca7a1f5-fbb1-4f24-9e42-6db4094da257)

**Comment by cortexrd** [comment]
Would it be ok to use **Command+S** instead of Alt+S?

**Comment by hwrainbird** [comment]
I don't see why not. Command+S is currently the shortcut for downloading a webpage (which I never use), would it override this?

**Comment by cortexrd** [comment]
Now this ends up being even more complicated!

I'll try to keep Alt+S but simply prevent adding that character.  How's that?

**Comment by hwrainbird** [comment]
Yup that would work!

**Comment by cortexrd** [comment]
Just uploaded new zip.  Give it a try.  **v1.6.0**

**Comment by hwrainbird** [comment]
Awesome, thank you :)

**Comment by hwrainbird** [comment]
Yup, this fixes it 👍🏻
