### ISSUE TITLE
New table button pushed off screen by search

### ISSUE THREAD

**Issue by hwrainbird** [cortexrd/Kneuron#12]
![Rainbird Apps Screenshot 2024-11-28 @ 14 57 26](https://github.com/user-attachments/assets/6a453a72-2b7f-46b1-a5c3-b4fbc0581488)

**Comment by cortexrd** [comment]
Try new zip, it fixes that.

**Comment by hwrainbird** [comment]
Nice that works, could we get the same fix on the Pages?

**Comment by cortexrd** [comment]
Done.

**Comment by cortexrd** [comment]
Harry,

Is this one good now?
