### ISSUE TITLE
Filter Pages to Copy/Move

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Kneuron#7]
Hi Norm
When first selecting a page to copy/move a view it seems to not select it properly and it always selects the first page in the list.

I can get it to select the correct page when I go back and reselect the correct page it selects it (Correct page) sometimes.

Craig

**Comment by CSWinnall** [comment]
Hi Norm

Here a video for this issue.  In the video it's hard to see there are 2 dropdowns you will have to trust me that there is.

https://www.loom.com/share/9fad2774482845a88a2ba413e02f8d30?sid=6d4d8fbe-ab93-4877-8893-af2364980f24

Craig

**Comment by cortexrd** [comment]
Very good catch!
It's fixed now.
Thanks :)

**Comment by CSWinnall** [comment]
Very Nice
Thank you
